### ISSUE TITLE
ch04/numberic.go: 4.1+3 correct no error

### ISSUE THREAD

**Issue by lifenglsf** [mactsouk/mGo4th#11]
![image](https://github.com/user-attachments/assets/6569544b-aa0f-4202-b400-8978ad47ab72)
![image](https://github.com/user-attachments/assets/9774e7b1-6e61-4d8d-ac9a-9fbb6aa15974)
got error under 1.21.0

**Comment by mactsouk** [comment]
```
$ go version
go version go1.23.1 darwin/arm64
$ go run ch04/numeric.go
4 + 3 = 7
4.1 + 3.2 = 7.3```

It looks like it is working.
